### ISSUE TITLE
Windows builds/distributables should include c header files

### ISSUE THREAD

**Issue by a-schild** [ImageMagick/ImageMagick6-Windows#1]
The current ImageMagick6 distributables don't include the .h files used to generate the exe/dll targets.

Due to this, it's not possible to build other libraries which require these to build.
THe ImageMagick 7 windows distributables/builds have the required .h filese included in them

Example project: https://github.com/techblue/jmagick

**Comment by dlemstra** [comment]
Can you explain in more detail what you think you are missing? The development headers are available for both ImageMagick 6 and 7.

**Comment by a-schild** [comment]
Sorry, my problem.
To get the dev headers I had to download the dll version and then check the checkbox to also install the headers/objects.

Thanks for your work
